FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y bc
RUN apt-get install -y gcc
RUN pip install cython
RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install matplotlib
RUN pip install sklearn
RUN pip install seaborn
RUN pip install xlsxwriter
RUN pip install pandas
RUN pip install tensorboard_logger
RUN pip install tensorboard
RUN pip install openpyxl
RUN pip install torchsummary
RUN pip install pytorch-model-summary
RUN pip install simplejpeg
RUN pip install pycocotools